//! Systematic layer-0 comparison test: our implementation vs PyTorch reference.
//!
//! Runs a single TransformerLayer forward pass with known input and compares
//! every intermediate tensor against PyTorch-generated reference values.

#[cfg(feature = "rocm")]
mod layer0_compare {
    use std::sync::Arc;
    use t0_gpu::ignis::gpu_context::GpuRuntime;
    use t0_gpu::ignis::tensor::{Tensor, DType};
    use t0_gpu::ignis::nn::Module;
    use t0_gpu::ignis::nn::linear::Linear;
    use t0_gpu::ignis::ops;

    /// Reference values from PyTorch for "What is 2+2?" (7 tokens), layer 0, last token.
    /// Generated by: python3 reference_layer0.py
    struct RefValues {
        // Per-step norms (all-token total)
        embed_norm: f32,
        h_norm_norm: f32,
        q_norm: f32,
        k_norm: f32,
        v_norm: f32,
        attn_out_norm: f32,
        proj_out_norm: f32,
        x2_norm: f32,
        h2_norm: f32,
        gate_norm: f32,
        up_norm: f32,
        silu_out_norm: f32,
        ffn_out_norm: f32,
        final_norm: f32,
    }

    const REF: RefValues = RefValues {
        embed_norm: 2.2587,
        h_norm_norm: 17.8678,
        q_norm: 46.1645,
        k_norm: 35.1166,
        v_norm: 11.3629,
        attn_out_norm: 13.8278,
        proj_out_norm: 14.6417,
        x2_norm: 14.5909,
        h2_norm: 14.1177,
        gate_norm: 134.4434,
        up_norm: 45.1125,
        silu_out_norm: 5.7852,
        ffn_out_norm: 14.5935,
        final_norm: 22.0684,
    };

    fn norm(data: &[f32]) -> f32 {
        data.iter().map(|x| x * x).sum::<f32>().sqrt()
    }

    fn check(name: &str, got: f32, expected: f32, tol_pct: f32) {
        let err_pct = ((got - expected) / expected * 100.0).abs();
        let status = if err_pct < tol_pct { "✓" } else { "✗" };
        eprintln!("  {} {}: got={:.4} ref={:.4} err={:.2}%", status, name, got, expected, err_pct);
        assert!(err_pct < tol_pct, "{}: got={} ref={} err={:.2}%", name, got, expected, err_pct);
    }

    #[test]
    fn test_layer0_single_token_norms() {
        let rt = Arc::new(GpuRuntime::new().expect("GPU runtime"));
        let device = &rt.device;

        // Load model
        let model_path = "/mnt/public/models/huggingface/Qwen3-0.6B";
        let (mut model, _config) = t0_gpu::ignis::safetensors::load_qwen3_model_from_dir(&rt, model_path)
            .expect("load model");

        // Single token: "Hello" (id=9707)
        let input_ids = vec![9707u32];
        let embed = model.embedding.forward_cpu(&input_ids).expect("embed");
        let embed_data = embed.to_f32_vec();
        check("embed_norm", norm(&embed_data), 0.8545, 0.1);

        // Layer 0
        let layer = &model.layers[0];
        let mut kv_cache = t0_gpu::ignis::kv_cache::KvCache::new(
            &rt,
            t0_gpu::ignis::kv_cache::KvCacheConfig {
                num_layers: 28,
                num_kv_heads: 8,
                head_dim: 128,
                max_seq_len: 40960,
            },
        ).expect("kv cache");

        let result = layer.forward_inference(&embed, 0, 0, &mut kv_cache).expect("layer0");
        let result_data = result.to_f32_vec();
        check("layer0_final_norm", norm(&result_data), 9.8942, 15.0);
    }

    #[test]
    fn test_weight_shapes_and_norms() {
        let rt = Arc::new(GpuRuntime::new().expect("GPU runtime"));
        let model_path = "/mnt/public/models/huggingface/Qwen3-0.6B";
        let (model, _config) = t0_gpu::ignis::safetensors::load_qwen3_model_from_dir(&rt, model_path)
            .expect("load model");

        let layer = &model.layers[0];

        // Check weight norms against reference
        let checks: Vec<(&str, &Tensor, f32)> = vec![
            ("wq", &layer.wq.weight, 45.39),
            ("wk", &layer.wk.weight, 31.37),
            ("wv", &layer.wv.weight, 27.27),
            ("wo", &layer.wo.weight, 37.37),
            ("w_gate", &layer.w_gate.weight, 64.97),
            ("w_up", &layer.w_up.weight, 45.86),
            ("w_down", &layer.w_down.weight, 46.54),
            ("attn_norm", &layer.attn_norm_gamma, 6.10),
            ("ffn_norm", &layer.ffn_norm_gamma, 16.39),
        ];

        for (name, tensor, expected_norm) in &checks {
            let data = tensor.to_f32_vec();
            let n = norm(&data);
            check(&format!("{}_norm", name), n, *expected_norm, 1.0);
        }
    }

    #[test]
    fn test_cpu_rmsnorm_matches_reference() {
        // Single-token RMSNorm: input = embedding of "Hello", gamma = layer0 attn_norm
        let rt = Arc::new(GpuRuntime::new().expect("GPU runtime"));
        let model_path = "/mnt/public/models/huggingface/Qwen3-0.6B";
        let (model, _config) = t0_gpu::ignis::safetensors::load_qwen3_model_from_dir(&rt, model_path)
            .expect("load model");

        let embed = model.embedding.forward_cpu(&[9707u32]).expect("embed");
        let gamma = &model.layers[0].attn_norm_gamma;

        // GPU RMSNorm
        let result = ops::rmsnorm::rmsnorm(&embed, gamma, &rt.device).expect("rmsnorm");
        let result_data = result.to_f32_vec();

        // Reference: norm=6.3095, first3=[-0.0051, -0.3908, 0.4231]
        check("rmsnorm_norm", norm(&result_data), 6.3095, 0.1);

        // Check first 3 values
        let ref_first3 = [-0.005116f32, -0.390828, 0.423056];
        for (i, (got, expected)) in result_data.iter().zip(ref_first3.iter()).enumerate().take(3) {
            let err = (got - expected).abs() / expected.abs().max(1e-6);
            assert!(err < 0.01, "rmsnorm[{}]: got={} expected={} err={:.4}", i, got, expected, err);
        }
    }
}
